### ISSUE TITLE
Thrallmar wolf riders

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1745]
Originally reported by: **Bulldoze (Bitbucket: [Legitcow](https://bitbucket.org/Legitcow), GitHub: Unknown)**

----------------------------------------

[Riders on l4g](http://i.imgur.com/X3pJXi9.jpg)

[Wowhead link](http://www.wowhead.com/npc=16599/thrallmar-wolf-rider)

Should be ride together, and far further than only to thrallmar gates.

[Video proof from retail](https://youtu.be/YcIsKmOL5I8?t=1m52s)

*Also, are their abilities working? I saw them getting rekt by small group of 60's allys
(didnt see the fight but their dead bodies next to couple of alliances*)

Edit: here we go again. Changing priority to major because Thrallmar must be protected well from the alliance.

off-topic: Do you guys think that Corecraft is a role model for L4G regarding bug fixes n stuff? Because if so , I can help you guys by checking how stuff works on CC to improve L4G's mechanics.

[Thrallmar wolf riders on corecraft](http://i.imgur.com/ea4oTXr.jpg)

Edit2: Saw them in combat today. They didn't dismount when aggroed and didn't use their abilities.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1650

**Comment by Saltgurka** [comment]
They are now on their proper waypoints, in a proper formation, and using the proper spells. It will be live in the next update. 

Dismounting Blast still does not dismount the player, but I've created a separate issue for that, since it's not related specifically to these mobs. https://github.com/Looking4Group/L4G_Core/issues/2858
