### ISSUE TITLE
Cloaking/Paiin Suppression/Vanishing spells in mid air does nothing.

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2511]
Originally reported by: **vendetta (Bitbucket: [vendetta43](https://bitbucket.org/vendetta43), GitHub: Unknown)**

---

At the moment if you pre cloak a shatter it will still go thru, this along with pain supression or vanish.

Example 1: my rogue pre-vanished a blind (his vanish is on cd) but yet he is in blind.
Example 2: my rogue pre cloak the shatter while the frostbolt / ice lance is in the air. BOTH hit.
Example 3: im nova'd and there is a frost bolt / ice lance in the air, and i pain sup it while it's in the air. both crit me for all my health , none of the dmg being reduced

there is something wrong with how spells are dealt with that are in the air. needs to recheck 

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2417

**Comment by AnonXS** [comment]
Only Immunity Spells work against Mid Air in TBC.

**Comment by robinsch** [comment]
That's wrong. Damage and immunity should be checked on hit (allowing mid air stuff). Resistance on cast.

**Comment by Evolvee** [comment]
thats wrong too, all spells are calculated on cast, not on hit, EXCEPT cheat death(blizzards hotfix) and immunity/vanish spells

whole shatter combo would not work if its calculated on hit

**Comment by robinsch** [comment]
That's wrong. FREEZING STATE is also checked on HIT. You can test it on retail, cast FB and dispel Nova while FB is flying.

The thing that allowed Shatter is that Frost Nova broke delayed on retail.

**Comment by Evolvee** [comment]
Then can u explain why did blizzard hotfix cheat death TWICE because it was not working against spells already in mid-air?

**Comment by robinsch** [comment]
Yes of course you get hit by it. Resistance were checked ON CAST. Immunity and damage reduction ON HIT.

**Comment by Anteara** [comment]
"For perspective, in patch 2.4 prior to LK, Vanish was more reliable in the situation I’m talking about above: used after a spell was cast would make you immune to the spell. It had some other bugs at the time, but all of those that we know about have been fixed. We have made many changes to the way spells work in the 3.X cycle, and one of them made the situation bad again. We need to get the conflict between missile travel time and Vanish resolved the way it used to work. The bad news is that since this is a code fix, it might not make it into 3.3. The good news is that because it is likely a server fix, it doesn’t need to wait for a major patch."

Ghostcrawler - 2009

"The way we want it to work: If you Vanish after a single targeted spell is cast, you’re safe, even if the missile is still in the air. If an AE spell is cast on you, even if you just went into stealth, it should break you out."


It implies < 2.4 patch, if something is in the air, and rogue casted vanish, he is immune for it.

**Comment by Evolvee** [comment]
yea but vanish is designed to do that, we are talking about whole "on cast/on hit" mechanic

**Comment by Anteara** [comment]
Reading this it kind of seems you guys are agreeing with each other, can you elaborate where the discrepancy is?

**Comment by Evolvee** [comment]
Imagine a situation where your target has frost nova. You cast ice lance and he dispels that frost nova while the ice lance missile is mid-air(launched). I said it should do tripple dmg(calculated when casted) and he said it should do basic normal dmg(calculated when landed).

and btw on retail you could do even tripple shatter(fb + double ice lance on max range) which would be impossible to do with only 400ms max delay

some evidence would be helpful.. because right now I have evidence(spells going through cloak/shatter/hunters autoshots being immuned by target who went out of cyclone etc) only for my case(calculation on cast).

**Comment by Evolvee** [comment]
http://us.battle.net/forums/en/wow/topic/7414944435

<Wanna Play>
110 Dwarf Warrior
14275
1473 posts
Dec 25, 2012



Dec 25, 2012

If multiple targets cast the spell at the same time then yes spell reflect will catch them all
but not 2 spells from one target such as an instant and a cast. otherwise if they reflect you two times quickly its spell reflect and mass spell reflect in succession


Incorrect. Both things can happen.

It's like the old shatter combo (wotlk) where the frostbolt hit as if you were in a nova cause you were at the time it was finished casting, even if at the time it hits you you were no longer in it cause the ice lances broke it.
That's cause spells calculate the hit at the moment of finishing the cast, not at landing.

**Comment by Evolvee** [comment]
there is some huge shitstorm going on about my last comment of spell reflect...

spell reflect shouldnt reflect spells that are mid-air while the reflect fades off ( http://www.wowhead.com/spell=23920/spell-reflection#comments:id=250228 )
It has to be in effect when the spell is cast AND when it hits you in order to reflect it (most noticeable with Incinerate).

so what the fuck is correct, cant trust anything and anyone
