### ISSUE TITLE
Druid/Talent - Natural Shapeshifter

### ISSUE THREAD

**Issue by Fatname** [Looking4Group/L4G_Core#2836]
I just noticed that the talent Natural Shapeshifter is bugged (Restoration tree)

The issue is that, when you are in shapeshift and going to shapeshift again with enough mana (580), you still need enough mana without this talent. 
Sorry for the bad English

http://db.looking4group.eu/?spell=16833 R1 , http://db.looking4group.eu/?spell=16834 R2 , http://db.looking4group.eu/?spell=16835 R3 , http://db.looking4group.eu/?spell=33891

Kind regards

**Comment by honeyhoney** [comment]
This is such a disappointing fix. Far too much time was invested in figuring out how auras that modify spell cost are applied to specific spells.

Turns out it's just a simple database update.

@AnonXS this should be all good for your next update. Highly recommend testing on PTR beforehand. In testing this locally I was checking as best as I could the mana cost reduction was being applied to shapeshifts only. I was able to (intentionally) get it to apply to other spells so I'm fairly confident the current spell mask includes only shapeshifts.

```
-- Update Natural Shapeshifter talents (rank 1-3) to include Tree of Life
UPDATE `spell_affect` SET `SpellFamilyMask`=527769339428864 WHERE `entry` IN (16833,16834,16835);
```

**Comment by honeyhoney** [comment]
@AnonXS any feedback?

**Comment by Fatname** [comment]
I have tried the same talent again and I can't find any flaws,  thanks a lot for this fix well done

**Comment by honeyhoney** [comment]
@Fatname I don't believe the fix is live yet. I just tested it quickly and it seems the Tree of Life shapeshift is still unaffected by the Natural Shapeshifter talent.

@AnonXS will this get added to one of your updates?

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2891/commits/78fdf2b57c101af026fc8296d2e001db2fe81431
