### ISSUE TITLE
Gnome racial Escape Artist does not remove Crippling Poison

### ISSUE THREAD

**Issue by rewerg** [Looking4Group/L4G_Core#2906]
http://wow.gamepedia.com/Escape_Artist

When i'm affected with http://wowwiki.wikia.com/wiki/Crippling_Poison_(item) and i'm using the racial, the effect and the slow remains on me, but the racial goes to CD.   Got this bug a few times today (13.10.16) in Battlegrounds. ( its possible that it doesnt remove other things, but i noticed it only with crippling poision)

**Comment by AnonXS** [comment]
http://www.wowhead.com/spell=20589/escape-artist#comments

to Classic

By Carighan (18,976 – 4·23·165) on 2006/12/03 (Patch 1.12.2)  
One should note that since 1.11 (could be 1.12, but not entirely sure) this seems to have a roughly 10% chance of failure.

to TBC

http://wowwiki.wikia.com/wiki/Escape_Artist

Brawndo on 2008/03/24 (Patch 2.3.3)
In addition druid's subtlety talent will interact with this and entangling roots, giving it a very unfortunate rate of failure.

http://wow.gamepedia.com/index.php?title=Escape_Artist&oldid=1588354

Escape Artist also counts as a "Dispel" effect rather than an "Immunity" effect. What this means is that talents that give you a "chance to resist dispel effects" can cause Escape Artist to fail. Such as the Rogue's [Vile Poisons] talent, which gives you a chance to prevent [Crippling Poison] from being Dispelled.

http://www.arenajunkies.com/topic/29908-vile-poisons-worth-it/

Against a team with no shaman, druid, or paladin, Improved Poisons is obviously superior, unless you like to see gnomes bash their head against their keyboard when Escape Artist fails to dispel Crippling Poison.

read on: http://www.arenajunkies.com/topic/11968-escape-artist-failed/ , https://redmine.rising-gods.de/issues/11628

to WOTLK

By Vayus (3,267 – 12·24) on 2008/10/25 (Patch 3.0.2)  
As of patch 3.0.2, this racial can no longer be resisted and fail. It will wipe all snares+roots 100% of the time guaranteed.
