### ISSUE TITLE
BUGS IN TERROKAR

### ISSUE THREAD

**Issue by Drakous** [Looking4Group/L4G_Core#3071]
Greetings,

I am doing quest Timber Worg Tails. I have to find 12 tails but drop rate is realy low.

 But there is one bigger bug. Very often I can not cast (texture problem) even if there is nothing between me and a mob. Sometimes I can cast but my spell disappears and do not hit a mob. Even my Mana Tide Totem did not give me mana (I was cca 5y away from it) cause there was some texture bug.

Please can someone fix it? Thanks. =)

**Comment by AbaddonL4G** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c53d722aa29ff3a39d881de7d6ef86b79deffe48

think this should fix it.

maybe could case issues in warsong gulch. (allready got a possible patch for it - not sure if need/want to implement).

**Comment by AnonXS** [comment]
To add to the Timber Worg Tails:

http://www.wowhead.com/item=25807/timber-worg-tail#comments
http://www.wowhead.com/quest=10016/timber-worg-tails#comments

By Fortinbrae (1,442 – 6·17) on 2007/04/17 (Patch 2.0.12)		
Drop rate is somewhere between non-existant and ridiculous, leaning towards ridiculous, since every worg you find has a large fluffy tail which somehow seems to disappear at the moment you deal the killing blow. Very odd.

By thegeoman (1,206 – 1·12) on 2007/05/11 (Patch 2.0.12)		
Its amazing how few wolves in Terrokar have tails. You'd swear it looks like they all have one, but once the kill is done, lo and behold, no tail. Reminds me of those mutant humans in Hillsbrad that have no skulls....
