### ISSUE TITLE
Quest: Aged Envelope - Durator

### ISSUE THREAD

**Issue by thestranger064** [Looking4Group/L4G_Core#3135]
In durator - in the human keep you can loot a key from Benedict an thus open a chest near the roof.
Opening chest just cloces the window, and the key dissapears.
Thus you cannot get this starting quest item, which turns into - The Admiral's Orders

**Comment by Saltgurka** [comment]
I've tried basically everything to make this work but something seems to be very wrong with this chest. Even copying data from another chest into this chest's template didn't work.

What I did discover however is that if you hold shift when opening the chest (instaloot) you will actually get the item, so that's even stranger

**Comment by AnonXS** [comment]
Remove Faction of 3239

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/ce2f4be95ea8cac4dfa201b945404dd3b0d4c570
