### ISSUE TITLE
Pristine Black Diamond

### ISSUE THREAD

**Issue by corbindallass** [Looking4Group/L4G_Core#3478]
Hi, I looked at year old posts on here about the Pristine Black Diamond, but with this being a new server I just wanted to confirm that it was a lootable item and that the drop rate is correct.  I've run most of Strath about 10 times, LBRS once and Scholo once.  Just making sure I'm not going crazy.  Thanks.

**Comment by AnonXS** [comment]
Highest Dropchance is about 2% with a total of 200 potential npcs dropping this item.

**Comment by AcidScytheZ** [comment]
Drop in this server gotta be bugged for sure. According to the other realm where i played 1-2 months when started before some time. I tried to get 1 diamond and was farming like 2 weeks. Never dropped. Finally bough it from person.

**Comment by ilaeli** [comment]
I would like to suggest increasing the drop rate or giving it to paladins for free. A great deal of horde players are here only because of Blood Elf Paladins.. It is incredibly unfair to expect them to clear old content with an super low drop rate just so they can get something that is special to the paladin class.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3516

**Comment by corbindallass** [comment]
Thank you...thank you.  It dropped tonight on my 3rd run.  Thank you!
