### ISSUE TITLE
 [Trial of the Naaru: Strength] - murmur Drop

### ISSUE THREAD

**Issue by Druidmastera** [Looking4Group/L4G_Core#3765]
If you die, or DC doing the fight with murmur, or if a party member loots the quest item before you get rezzed, You will not be able to loot that the quest item, and complete the quest that day.

**Comment by AnonXS** [comment]
Well, was the issue that the boss was already despawned, was the issue that the boss corpse was lootable but empty etc, maybe it could be prevented by the groupmembers not looting but from what i can tell thats simple abuse prevention as people could find a way around when the lootsystem wouldnt be written as "hard" as it is now, but overall yes the lootsystem could need an enhancement or two, which should not be adressed in specific creature loot issues but as general issues discribing the actual underlying problem, proposing a potential to change or a general idea on what to do otherwise when a group/raid loots a dead mob.
