### ISSUE TITLE
Moonstalker Runt in Darkshore are too high level

### ISSUE THREAD

**Issue by adnanberberovic** [Looking4Group/L4G_Core#3775]
Moonstalker Runts shouldn't be lvl 16-17. They're one of the first mobs you encounter, in a level 10-20 zone, so they should be the same level as thistle bears and similar entry level mobs in darkshore (level 11-12 ish).

moonstalker runt: http://db.hellfire-tbc.com/?npc=2070

thistle bear for comparison: http://db.hellfire-tbc.com/?npc=2163

**Comment by AnonXS** [comment]
http://www.wowhead.com/npc=2070/moonstalker-runt#comments

By WonderGamer (706 – 8) on 2009/10/10 (Patch 3.2.2)		
Correct level range is 16-17. Data got warped because somebody uploaded data taken while they were drunk.
Last edited by WonderGamer on 2009/10/10 (Patch 3.2.2)

kahjokaapio on 2010/04/21 (Patch 3.3.3)
No they are level 10-11. I just tamed one on my horde hunter. The level 16-18 ones are Moonstalker sires.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3755/commits/ddd5236b986f0f841ed85f83ea7b6c5f64d854d0

**Comment by Xadras** [comment]
shouldn't it be more like 10-17 then regarding the sources?

**Comment by AnonXS** [comment]
Well from my ep, this is either wrong, or we can not simulate the state where in the north there are more lower levels, in the south more higher levels and as its just the "Runt" i left it with lower levels only.
