### ISSUE TITLE
Sunfury Warlocks in Ruins of Karabor area of SMV have issues

### ISSUE THREAD

**Issue by Russet0** [Looking4Group/L4G_Core#3812]
The Sunfury Warlocks in Ruins of Karabor above Black Temple are killed to drop a scroll that releases Azaloth, the demon they are channeling to keep banished, for the quest A Necessary Distraction.

When they are attacked they are supposed to stop channeling and attack the player. This does not release the demon, using the item they drop does.

However, current behavior can look like this: http://i.imgur.com/Gu3V4NY.jpg

Problems:
- Dead bodies can continue to channel, both with or without beams
- Warlocks aggroed to the player do not stop channeling
- When aggroed, they twitch back and forth a yard or two from their spawn point, trying to attack the player but aborting and going back to channeling at their spawn, over and over.

Another issue is that the demon Azaloth immediately attacks the player when unbanished through the quest item that is looted from the warlocks. I do not believe this is intended behavior, you should have time to get away before he attacks anything.

Here is a video demonstrating the retail behavior (from 2012 with a higher level cap): https://www.youtube.com/watch?v=_NPAIXkTFpY

NPC: http://db.hellfire-tbc.com/?npc=21503
Relevant quests (Aldor & Scryer): http://db.hellfire-tbc.com/?quest=10637
http://db.hellfire-tbc.com/?quest=10688

**Comment by AnonXS** [comment]
Connected to ugly core script for the demon Azaloth they banish.

**Comment by Saltgurka** [comment]
https://bitbucket.org/Caboon/playcore-official/commits/78c4997cbec26a5eb0ec44842fa2aec76606b229

**Comment by Saltgurka** [comment]
Sunfury Warlocks will be fixed with https://github.com/Looking4Group/L4G_Core/pull/3825, and Azaloth is improved as well. 

The delay you're mentioning is not present in this video: https://www.youtube.com/watch?v=Nn_fDNtOKUw

Judging by wowhead comments he should be killing other mobs in the area after you unbanish him and eventually Alandien should come and have some sort of event: http://www.wowhead.com/quest=10637/a-necessary-distraction#comments:id=48844 http://www.wowhead.com/quest=10637/a-necessary-distraction#comments:id=201231

> Fun note- after Azaloth kills the warlocks, he'll fight one of the 70 elite Demon Hunters.

> Alandien comes and slaughters him if you ignore him after Unbanishing him. Slightly entertaining. She absolutely OWNS him. He doesn't stand a chance.

Would require more research before implementing

**Comment by AnonXS** [comment]
I currently made him "passive" as the banish wasnt working either after he was unbanised once, so if his script fixes that flaw, him being "banised but still able to attack" i will make him attack on his own accord again after this update.
