### ISSUE TITLE
Improved Leader of the Pack - Vashj

### ISSUE THREAD

**Issue by Bbenna** [Looking4Group/L4G_Core#3881]
When a feral druid with specced Improved Leader of the Pack - http://wowwiki.wikia.com/wiki/Improved_Leader_of_the_Pack - Gets mc'd in P3 of Vashj, she will heal for 270k hp for every crit she does. Just wondering if this is intended, since I healed her for almost 1 million hp last time I had it specced and got mind controlled.

**Comment by AnonXS** [comment]
The main problem is mind control. This is a major problem with the encounter because it **can control anyone, even all the tanks who's tanking her. You have to raid with insane amounts of dps which we can live with until they get mind controlled (+200% damage and 1000% healing) and start one shoting each other** or **healing Vashj for over 50k.**

http://www.thecostaclan.com/phpBB3/viewtopic.php?f=10&t=6366

---

http://www.verdammtehorde.de/%C3%B6ffentliche-diskussion-2/lady-vashj-world-first-kill-by-nihilum-150/p1.html
