### ISSUE TITLE
Warlock Enslave Demon level 3

### ISSUE THREAD

**Issue by kuramajssken001** [Looking4Group/L4G_Core#3904]
Enslave Demon level 3 
level 62+ minions cannot be enslaved, but  creature level 70 can enslave Now.

**Comment by AnonXS** [comment]
depends on creature, what creature cant be enslaved?

**Comment by kuramajssken001** [comment]
Only Enslave Demon Rank 3 is wrong.

**Comment by AnonXS** [comment]
I can enslave high level demons with http://db.hellfire-tbc.com/?spell=11726 dk what the issue is.

**Comment by kuramajssken001** [comment]
Enslave Demon Rank 3
Level 62 + cannot be enslaved.

**Comment by honeyhoney** [comment]
For clarity:

#### Enslave Demon Rank 3 (http://db.hellfire-tbc.com/?spell=11726)
**Expected Behaviour:** you should be able to enslave all demons up to (this seems to imply it is inclusive) level 62. All demons level 63 or above should not be able to be enslaved by this spell.
**Expected Behaviour:** all demons, including those level 63 and above are currently able to be enslaved by this spell

**Comment by AnonXS** [comment]
Never heared of bullshit blizzard tooltips?

---

By biohazrd (1,145 –  5·15)  on 2007/04/23 (Patch 2.0.12)
Can be enslaved and banished.

http://www.wowhead.com/npc=16539/homunculus#comments

**Comment by kuramajssken001** [comment]
@AnonXS @honeyhoney thanks!
